// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7CA9U_BoVFxyzI9xRvlZEK1ncc7Z5jhg',
    appId: '1:86398548424:web:bfad1f720773a72315e8fd',
    messagingSenderId: '86398548424',
    projectId: 'kashya-be77e',
    authDomain: 'kashya-be77e.firebaseapp.com',
    storageBucket: 'kashya-be77e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrxHjS1sqjiw4xLLLnYvbyT1bvtDozDXs',
    appId: '1:86398548424:android:7d29824dfe06a13015e8fd',
    messagingSenderId: '86398548424',
    projectId: 'kashya-be77e',
    storageBucket: 'kashya-be77e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVLWicIFGWmqSMWaw27LEfVyiJ2KKqjF0',
    appId: '1:86398548424:ios:41b5bade03f7490f15e8fd',
    messagingSenderId: '86398548424',
    projectId: 'kashya-be77e',
    storageBucket: 'kashya-be77e.appspot.com',
    iosClientId: '86398548424-g7d9l4o7ijlt7ufqucp2l8161jc125jp.apps.googleusercontent.com',
    iosBundleId: 'com.example.classManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVLWicIFGWmqSMWaw27LEfVyiJ2KKqjF0',
    appId: '1:86398548424:ios:41b5bade03f7490f15e8fd',
    messagingSenderId: '86398548424',
    projectId: 'kashya-be77e',
    storageBucket: 'kashya-be77e.appspot.com',
    iosClientId: '86398548424-g7d9l4o7ijlt7ufqucp2l8161jc125jp.apps.googleusercontent.com',
    iosBundleId: 'com.example.classManagement',
  );
}
